nome = str(input('Digite seu nome completo: '))
print('-------------')
nome = nome.upper().strip()
print('Seu nome em maiúsculo:', (nome))
nome.split()
print('-------------')
nome2 = nome.lower()
print('Seu nome em minúsculo:', (nome2))
print('-------------')
separado = nome.split()
indice = len(nome)
espaços = nome.count(' ')
print('O nome contém {} letras'.format(indice - espaços))
print('-------------')
print('O primeiro nome contém {} letras'.format(len(separado[0])))
