n1 = float(input('Digite um número: '))
n2 = float(input('Digite um segundo número: '))
n3 = float(input('Digite um terceiro número: '))
x = max(n1, n2, n3)
z = min(n1, n2, n3)
print('O maior número é {:.2f}'.format(x))
print('O menor número é {:.2f}'.format(z))
